### PR TITLE
fix(ds,uss): Check if profile is invalid before searching

### LINKED ISSUE #2454: Disabling "Automatic Profile Validation" breaks search prompt for all 3 trees
_(credits to @YvesMichon for bringing this issue to our attention: see #2344)_

**Describe the bug**

Disabling the "Automatic Profile Validation" feature in Zowe Explorer's extension settings will prevent the search prompt from working across all three tree views (DS, USS, jobs).

**To Reproduce**

1. CTRL/Command + , (comma) to open Extension Settings
2. Navigate to "Zowe Explorer" section
3. Disable the setting "Automatic Profile Validation" (ensure it is disabled for the workspace and the user settings)
4. Reload the window: CTRL/Command + P -> "Developer: Reload Window"
5. Try clicking on the search icon beside a profile in any tree.
6. Notice that the search box does not appear, and no error is printed.

**Expected behavior**

- Is this an intentional outcome?
  - End users using a Zowe Explorer version below 2.9.0 do not encounter this problem. We should allow users to execute the search actions even if their profile is not validated.
  - _However_, if the behavior is intentional, and just happened to be broken before 2.9.0, we should at least provide a warning to users who are trying to search with profiles that are not validated. As it currently stands, this is considered a breaking change/regression for users who do not have automatic validation enabled.

**Desktop (please complete the following information):**

- OS: Windows or macOS
- Zowe Explorer Version: 2.9.0 and above

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

This PR fixes the following bug: when "Automatic Profile Validation" is disabled, the search prompts do not appear after clicking on the search icon for all 3 trees.

This was resolved for the jobs tree as a part of #2440, but the issue remained for the data set and USS trees.

Fixes #2454, #2344 

## Release Notes

Milestone: 2.11.0

Changelog:

- Fixed issue where disabling "Automatic Profile Validation" caused the search prompts to stop appearing for all tree views. #2454 

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

File: packages/zowe-explorer/src/dataset/DatasetTree.ts [hunk 1]
```diff
@@ -159,7 +159,7 @@ export class DatasetTree extends ZoweTreeProvider implements IZoweTree<IZoweData
             }
             const validationStatus = await Profiles.getInstance().checkCurrentProfile(element.getProfile());
 
-            if (validationStatus.status === "unverified") {
+            if (SettingsConfig.getDirectValue(globals.SETTINGS_AUTOMATIC_PROFILE_VALIDATION) && validationStatus.status === "unverified") {
```
Comment (JillieBeanSim) [inline packages/zowe-explorer/src/dataset/DatasetTree.ts:162]: unverified should still initiate search and either return something or error.  Turning off validation of profile just eliminates the call to check if server is running.

File: packages/zowe-explorer/src/job/ZosJobsProvider.ts [hunk 2]
```diff
@@ -199,7 +199,7 @@ export class ZosJobsProvider extends ZoweTreeProvider implements IZoweTree<IZowe
             }
             const validationStatus = await Profiles.getInstance().checkCurrentProfile(element.getProfile());
 
-            if (validationStatus.status === "unverified") {
+            if (SettingsConfig.getDirectValue(globals.SETTINGS_AUTOMATIC_PROFILE_VALIDATION) && validationStatus.status === "unverified") {
```
Comment (JillieBeanSim) [inline packages/zowe-explorer/src/job/ZosJobsProvider.ts:202]: same as before, should still initiate search

File: packages/zowe-explorer/src/uss/USSTree.ts [hunk 3]
```diff
@@ -297,7 +297,7 @@ export class USSTree extends ZoweTreeProvider implements IZoweTree<IZoweUSSTreeN
                 return favsForProfile;
             }
             const validationStatus = await Profiles.getInstance().checkCurrentProfile(element.getProfile());
-            if (validationStatus.status === "unverified") {
+            if (SettingsConfig.getDirectValue(globals.SETTINGS_AUTOMATIC_PROFILE_VALIDATION) && validationStatus.status === "unverified") {
```
Comment (JillieBeanSim) [inline packages/zowe-explorer/src/uss/USSTree.ts:300]: same, initiate search without checking if server is running

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
I tried a search with validation turned off and was only allowed the results of search when turned validation back on.  This is not the way, unvalidated profiles should still make api calls and either return results or error.

File: packages/zowe-explorer/src/dataset/DatasetTree.ts (hunk 1 above)
Comment (traeok) [reply packages/zowe-explorer/src/dataset/DatasetTree.ts:162]: The `validationStatus.status === "unverified"` check was added in 40b10157, but I agree, I don't think it's needed. I didn't want to re-introduce the "Update Creds" loop and this was done as part of that PR, so I wanted to make the changes as minimal as possible. I will remove it

File: packages/zowe-explorer/src/uss/USSTree.ts (hunk 3 above)
Comment (traeok) [reply packages/zowe-explorer/src/uss/USSTree.ts]: resolved in [f85c661](https://github.com/zowe/vscode-extension-for-zowe/pull/2461/commits/f85c66102a748b6dc962e84ec38eed2eee59e45c)

File: packages/zowe-explorer/src/dataset/DatasetTree.ts (hunk 1 above)
Comment (traeok) [reply packages/zowe-explorer/src/dataset/DatasetTree.ts]: resolved in [f85c661](https://github.com/zowe/vscode-extension-for-zowe/pull/2461/commits/f85c66102a748b6dc962e84ec38eed2eee59e45c)

**Review by JillieBeanSim — APPROVED** [review]
Thanks for pushing the updates @traeok unverified profiles are working as expected now.  Sorry, didn't realize that other check got introduced and merged in.
We introduced the option of disabling the server check for slow connections to cut down on the extra api calls and the hold/wait for the verification to complete before next action.

**Comment by traeok** [comment]
> Thanks for pushing the updates @traeok unverified profiles are working as expected now. Sorry, didn't realize that other check got introduced and merged in. We introduced the option of disabling the server check for slow connections to cut down on the extra api calls and the hold/wait for the verification to complete before next action.

No worries, thanks again for reviewing/testing 😁
