### PR TITLE
Don't load project profiles when no workspace folder is open

### LINKED ISSUE #1802: Project profiles loaded when no workspace folder is open
**Describe the bug**

A Team profile in `~` (e.g. `/root/zowe.config.json`) may be treated as a project configuration file when no workspace is open on VSCode.

**To Reproduce**

1. Create a valid `zowe.config.json` (and schema) file in `/root` 
2. Open VSCode (and make sure no folders are open)
3. Open Zowe Explorer
4. Notice that profiles from the team config (step 1) are loaded as project profiles.

**Expected behavior**

No project profiles being loaded if there is no workspace open.

**Screenshots**

temp

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Zowe Explorer Version: 2.0.1
- (Optional) Zowe CLI Version: 7.1.3
- (Optional) Are you using Secure Credential Store? y

**Additional context**

The gif above is from this comment https://github.com/zowe/vscode-extension-for-zowe/issues/1777#issuecomment-1124870664, which introduces environmental variable support (more details? #1777)

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Fix #1802 by falling back to an empty string for the project directory when the VS Code workspace root is undefined.

This depends on Zowe CLI 7.6.1 which includes an update to the Imperative ProfileInfo API that skips loading project profiles when `projectDir` is `false`.

## Release Notes

Milestone: 2.4

Changelog: Updated with TBD Release

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

## Further comments

See #1802 for steps to reproduce the issue and verify the fix.

### CODE REVIEW

File: packages/zowe-explorer/src/utils/ProfilesUtils.ts [hunk 1]
```diff
@@ -249,7 +249,7 @@ export async function readConfigFromDisk() {
             rootPath = vscode.workspace.workspaceFolders[0].uri.fsPath;
             await mProfileInfo.readProfilesFromDisk({ homeDir: getZoweDir(), projectDir: getFullPath(rootPath) });
         } else {
-            await mProfileInfo.readProfilesFromDisk({ homeDir: getZoweDir() });
+            await mProfileInfo.readProfilesFromDisk({ homeDir: getZoweDir(), projectDir: "" });
         }
```
Comment (zFernand0) [inline packages/zowe-explorer/src/utils/ProfilesUtils.ts:253]: should we simplify this if/else 😋 (similar to other places)
`vscode.workspace.workspaceFolders?.[0].uri.fsPath ?? "",`

**Review by zFernand0 — COMMENTED** [review]
LGTM!
Just need the changelog update

File: packages/zowe-explorer/src/utils/ProfilesUtils.ts (hunk 1 above)
Comment (JillieBeanSim) [reply packages/zowe-explorer/src/utils/ProfilesUtils.ts:253]: This is in the ZE API ProfilesCache so no vscode specific code in this file.  There will need to be a check for this.cwd being the OS's home directory if possible

File: packages/zowe-explorer-api/src/profiles/ProfilesCache.ts [hunk 2]
```diff
@@ -70,7 +70,7 @@ export class ProfilesCache {
 
     public async getProfileInfo(): Promise<zowe.imperative.ProfileInfo> {
         const mProfileInfo = new zowe.imperative.ProfileInfo("zowe");
-        await mProfileInfo.readProfilesFromDisk({ homeDir: getZoweDir(), projectDir: this.cwd });
+        await mProfileInfo.readProfilesFromDisk({ homeDir: getZoweDir(), projectDir: this.cwd ?? "" });
```
Comment (JillieBeanSim) [inline packages/zowe-explorer-api/src/profiles/ProfilesCache.ts:73]: should there be a check for if this.cwd is the OS's home directory?

Comment (JillieBeanSim) [reply packages/zowe-explorer-api/src/profiles/ProfilesCache.ts:73]: something similar to this fashion `const homedir = require('os').homedir();`

Comment (t1m0thyj) [reply packages/zowe-explorer-api/src/profiles/ProfilesCache.ts:73]: The scenario I have tested so far with this PR is when there is no workspace open in VS Code, to ensure that project config is not loaded. The scenario you mentioned seems different - if the project directory is the same as my home directory, we don't want the config files in the home directory to get loaded twice. Is that right? No objections to testing that scenario as well and making sure this PR handles it correctly, just want to make sure we're on the same page 🙂

File: packages/zowe-explorer/src/utils/ProfilesUtils.ts (hunk 1 above)
Comment (t1m0thyj) [reply packages/zowe-explorer/src/utils/ProfilesUtils.ts:253]: I'd like to make that simplification but am not sure if I can here because the `getFullPath` method is called inside the if statement. I suppose this raises the question of whether `getFullPath` should be called in the file above (`ZoweExplorerExtender.ts`), because it isn't currently?

Comment (zFernand0) [reply packages/zowe-explorer/src/utils/ProfilesUtils.ts:253]: good catch! 🤔 
Maybe it should be called in both since we've had issues with windows file paths before 👍

**Comment by t1m0thyj** [comment]
In the process of writing unit tests for this PR, discovered some issues with changes made to Imperative. Moved this PR back to draft mode until https://github.com/zowe/imperative/pull/888 is published in Zowe CLI.

File: packages/zowe-explorer-api/src/profiles/ProfilesCache.ts (hunk 2 above)
Comment (t1m0thyj) [reply packages/zowe-explorer-api/src/profiles/ProfilesCache.ts]: Added unit tests to verify that loading profiles from home directory and project directory behaves correctly.

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋
