### PR TITLE
Fix: bugs found for edit session

### LINKED ISSUE #748: Pressing Escape does not abort Edit profile dialogue
When I click the pencil button to edit a profile I get an input box as expected

Screenshot 2020-04-29 at 11 36 10

When I press Escape, the input box does not cancel the wizard but progresses to next input box 
Screenshot 2020-04-29 at 11 52 48

### LINKED ISSUE #767: Editing cred to spaces
If I edit the profiles and change it to spaces, the prompt is not triggered

### PR DESCRIPTION
**Pull request by jellypuno**
### Addresses:
**Fix #767** - Editing of Credentials and setting them to spaces
**Fix #748** - Pressing Escape does not abort Edit profile dialogue

### Details:
The prompt function is triggered if the profile is changed to spaces
When you press escape when editing the URL, it will not go through the next dialogue box

### Release Notes:
**Milestone:** v1.5.1
**Changelog:** Fix bugs for edit session

### CODE REVIEW

File: src/abstract/ZoweTreeProvider.ts [hunk 1]
```diff
@@ -126,16 +126,15 @@ export class ZoweTreeProvider {
...
         const EditSession = await Profiles.getInstance().editSession(profile, profileName);
-
         if (EditSession) {
             node.getProfile().profile= EditSession as IProfile;
-            setProfile(node, EditSession as IProfile);
-            setSession(node, EditSession as ISession);
-            this.refresh();
+            await setProfile(node, EditSession as IProfile);
+            await setSession(node, EditSession as ISession);
+            await this.refresh();
```
Comment (Pranay154) [inline src/abstract/ZoweTreeProvider.ts:137]: Does the `await` affect the `this.refresh()`?

Comment (jellypuno) [reply src/abstract/ZoweTreeProvider.ts:137]: yes, as far as I could see. It will wait for setProfile and setSession before refreshing. If I remove the await it will execute first and not wait for the other functions. which is something that I do not want.

Comment (Pranay154) [reply src/abstract/ZoweTreeProvider.ts:137]: I see, the reason I asked was because to my understanding, the `this.refresh()` isn't an `async` function so it doesn't return a `Promise`, so I don't think the `await` is needed and it won't affect the order of execution.

Comment (jellypuno) [reply src/abstract/ZoweTreeProvider.ts]: removed

**Comment by zFernand0** [comment]
Similar to #748, if you try a search, but you escape out of the username or password input fields, you are still asked for the searchFilter.

As for #767, you still get the error message if you hit enter multiple times in the username or password fields. But it at least ask twice.

I'm good with the fixes though.
